import raw from '../../generated/github-activity.json';

// Typed accessor for the build-time GitHub activity blob (1.15). The JSON is
// generated by scripts/fetch-github-activity.mjs and gitignored; this module
// gives it a stable shape regardless of what the fetch produced.

export interface ActivityItem {
  ts: string;
  repo: string;
  message: string;
}

export interface GithubActivity {
  source: 'github' | 'stub';
  fetchedAt?: string;
  message?: string;
  items: ActivityItem[];
}

export function getActivity(): GithubActivity {
  const a = raw as GithubActivity;
  // Spread keeps optional props absent-when-absent (exactOptionalPropertyTypes);
  // only `items` is normalized so the panel can always map over it.
  return { ...a, items: a.items ?? [] };
}
