// Typed accessor for the build-time city-buildings.json. The JSON is
// regenerated by `scripts/fetch-github-repos.mjs` (gitignored output).

export type District = 'trading' | 'research' | 'infrastructure' | 'ml' | 'lab';
export type BuildingStyle =
  | 'industrial'
  | 'fortress'
  | 'glass'
  | 'distributed'
  | 'asymmetric'
  | 'brutalist'
  | 'hexagonal'
  | 'static'
  | 'container'
  | 'default';

export interface BuildingData {
  readonly id: string;
  readonly name: string;
  readonly description: string | null;
  readonly url: string;
  readonly district: District;
  readonly primaryLanguage: string;
  readonly additions: number;
  readonly commits: number;
  readonly archived: boolean;
  readonly pushedAt: string;
}

export interface CityBuildingsManifest {
  readonly source: 'github' | 'stub';
  readonly fetchedAt: string;
  readonly buildings: ReadonlyArray<BuildingData>;
  readonly reason?: string;
}

import manifest from '../../generated/city-buildings.json';

export function getCityBuildings(): CityBuildingsManifest {
  return manifest as unknown as CityBuildingsManifest;
}

export const LANGUAGE_TO_STYLE: Record<string, BuildingStyle> = {
  Python: 'industrial',
  Rust: 'fortress',
  TypeScript: 'glass',
  JavaScript: 'glass',
  Go: 'distributed',
  'Jupyter Notebook': 'asymmetric',
  C: 'brutalist',
  'C++': 'brutalist',
  Solidity: 'hexagonal',
  HTML: 'static',
  CSS: 'static',
  Shell: 'container',
  Dockerfile: 'container',
};

export function styleFor(language: string): BuildingStyle {
  return LANGUAGE_TO_STYLE[language] ?? 'default';
}
